### ISSUE TITLE
Waves plug-ins

### ISSUE THREAD

**Issue by mzanibelli** [psycha0s/airwave#34]
Hi,

First of all, thanks a lot for your work.

I wanted to report a problem I tried to investigate for days : how to get Waves plug-ins running.

Disclaimer : i'm a former pro audio producer and a web developer, not at ease with this kind of bridges programs at all.

Background info :
- system : 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
- bitwig : 1.3.6
- wine : 1.9.2
- waves : 9.30 or 7.1.1.6
- graphics : nvidia GeForce 9500 GT (340xx)

I've been testing a lot of combinations between :
- architecture (32 or 64 bits)
- wine version (same results for all versions from 1.7 to 1.9, not detailed)
- wine prefix
- graphics driver
- waves version (as said 9.3 or 7.1.1.6)

I don't have any waves 7.1.1.6 in my 64bits prefix installed (N/A results)
My ultimate goal is to make waves 9.3 32bits working with nvidia drivers 
See second attachment for the mentionned GUI issue

It seems to be OPENGL related althought I wanted to give you more info about this.

![issue](https://cloud.githubusercontent.com/assets/16936745/12644307/4efecbea-c5c2-11e5-9b47-e2d395b25a89.png)

![gui](https://cloud.githubusercontent.com/assets/16936745/12644313/53118e20-c5c2-11e5-971f-af53c0a136b0.png)

I can provide more logs. Just don't know where to look ! I don't even know if you can do something about this issue as it seems really low-level related.

This is the one and only problem that keeps me stuck with Windows/OSX in the studio right now. I can't live without L2, Soundshifter and friends...

Thanks again.

Mat

**Comment by phantom-code** [comment]
Hi, Mat!

What airwave version have you tested? It's possible that latest version from the develop branch has a regression with shell plugins. I recommend you to test version 1.2.1 (if you didn't do this already).
Do you use a 32-bit wine prefix? As practice shows, there is no reason to use 64-bit wine prefix for audio plugins (maybe with an exception of Kontakt and Omnisphere).

Thanks for your report, I will definitely check this issue and let you know if I can do something.

**Comment by mzanibelli** [comment]
Well I forgot to mention a few things... This is a long story !

- i'm using Arch's AUR airwave-git package, daily updated ;)

- using "shell2vst.exe" I unpacked all my waveshells to plugin units - I had to run a windows 64bits vm to unpack 64bits Waves because Wine can't handle "shell2vst64.exe".

- I had the exact same problem with Fabfilter plugins (GUI issue screenshot) but I loaded them in 64bits and they worked. That simply means that the cause is the libgl used in 32 bits. For nouveau -> lib32-mesa-libgl (works but kernel panic when too many instances running), and for Nvidia -> lib32-nvidia-340xx-libgl (GUI issue)

I will definitely run more tests with Airwave 1.2.1 and maybe even a brand new clean 32bits prefix, I'll keep you posted.

**Comment by spectromas** [comment]
@mzanibelli did you find out any more information on this? I am experiencing similar problems to the ones you describe (stability problems with nouveau and gui issues with Nvidia) but using reaper in wine (not using airwave).

**Comment by mzanibelli** [comment]
@spectromas unfortunately I didn't find any solution to this problem. But it confirms Airwave got nothing to do with this though. Please keep me posted if you eventually manage to get something working.

**Comment by spectromas** [comment]
@mzanibelli I recently changed from manjaro to kde neon (ubuntu based) and I am able to view the guis with nvidia now. There is still a problem in that the vst will freeze the host when I try to remove it after opening the gui. This is from within renoise, the last part could possibly be airwave related but Im not sure. If there are any package versions you want to cross check then just let me know, I guess there could be quite a lot of variables which could make a difference. It hasn't really solved the issue for me as such but at least partially.

**Comment by mzanibelli** [comment]
@spectromas thanks for your feedback. That's a very interesting point because it made me think this could be related to compositing technologies used by the window manager. Since I'm now using i3wm and these programs (ie. "compton") are easily disabled, i'm gonna run more tests. I'll let you know about that, and i'll try to see if I can reproduce the bug that happens on removal.

**Comment by quinton-ashley** [comment]
Has any progress been made on getting Waves plugins to work?

**Comment by simudream** [comment]
Any news related to this issue?

**Comment by opendeepin** [comment]
hello 
 I speak spanish...  waves v9r2    working !!   airwave 1.3  portable
probado en  : Distro : Deepin linux  15.5
deepin crossover : botella xp
daw:  reaper native linux 5.71 rc2

[](https://ibb.co/ffhq0n)

**Comment by mzanibelli** [comment]
One year old issue with a cool tutorial :-)
